# Site settings
title: Gards | Developer
email: gards.ladines@gmail.com
description: > # this means to ignore newlines until "baseurl:"
   A portfolio site by using Jekyll nad Github Pages.
baseurl: '/gards-site'
url: "http://sdt4-site.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
permalink: /:title